cmake_minimum_required(VERSION 3.20)
project(CLesson C)

add_executable(DynamicArray DynamicArray.c)
add_executable(AVLTree AVLTree.c)
add_executable(pointer pointer.c)
add_executable(FuncPointer1 FuncPointer1.c)
add_executable(FuncPointer2 FuncPointer2.c)
add_executable(IndefiniteDocument IndefiniteDocument.c)
add_executable(CombSort CombSort.c)

add_executable(GainSeat LanQiao/GainSeat.c)
add_executable(AccessControl LanQiao/AccessControl.c)
add_executable(BalloonColor LanQiao/BalloonColor.c)
add_executable(FreshmanProtect LanQiao/FreshmanProtect.c)
add_executable(LineFollowingCar LanQiao/LineFollowingCar.c)

add_executable(TwoSum LeetCode/TwoSum.c)
add_executable(SumList LeetCode/SumList.c)
